### ISSUE TITLE
MapInit is not defined, as far as I can tell

### ISSUE THREAD

**Issue by thujone** [stephenscaff/google-maps-es6#1]
Your example initializer calls Map.MapInit(), but I don't see it defined anywhere

**Comment by stephenscaff** [comment]
Yeah.... my bad. I just updated a few things. 

Now, as seen in `src/index.js`, pass your map selector and api key to `GMap($mapEl, $apiKey)`

```
import * as Map from './GMap'
Map.GMap('.js-map', 'YOUR_GOOGLE_MAPS_API_KEY_HERE')
```
